### ISSUE TITLE
env IP4_PROVIDER configuration is ignored and cloudflare.trace error on 1.15.1 +

### ISSUE THREAD

**Issue by a-neagoe** [favonia/cloudflare-ddns#1032]
Problems: 

Latest versions, including alpine do not take in consideration my IPV4_PROVIDER from env (I have tried local, my isp ddns with a url:HTTP:/domain and https://api4.ipify.org) and the container is defaulting to Use default IP4_PROVIDER=cloudflare.trace. 

With the latest versions (tag lates, alpine or 1.15.1) that means the IPV4 would not update at all although my browser is loading fine the "
https://1.1.1.1/cdn-cgi/trace" and is giving me the correct IP address.
The standard log error for those versions is:

😞 Failed to send HTTP(S) request to "https://api.cloudflare.com/cdn-cgi/trace": GET https://api.cloudflare.com/cdn-cgi/trace giving up after 1 attempt(s): context deadline exceeded
😞 Failed to detect the IPv4 address

If I use 1.15.0 the default IP4_PROVIDER=cloudflare.trace, env is completely ignored but the IP is updated correctly.

Here are the complete settings:

Docker-compose:

```
services:
  cloudflare-ddns:
    image: favonia/cloudflare-ddns:1.15.0
    container_name: favonia-ddns
    network_mode: host
    restart: always
    user: "1047:100"
    read_only: true
    cap_drop: [all]
    security_opt: [no-new-privileges:true]
    environment:
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
      - DOMAINS=${MY_DOMAINS}
      - PROXIED=true
      - IPV4_PROVIDER=url:https://api4.ipify.org
      - IP6_PROVIDER=none
      - UPDATE_CRON=*/30 * * * *
      - TZ=${TZ}
```
docker inspect:

```
"Config": {
            "Hostname": "DS220",
            "Domainname": "",
            "User": "1047:100",
            "AttachStdin": false,
            "AttachStdout": true,
            "AttachStderr": true,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "DOMAINS=mydomains.eu,mydomains.eu",
                "PROXIED=true",
                "IPV4_PROVIDER=url:https://api4.ipify.org",
                "IP6_PROVIDER=none",
                "UPDATE_CRON=*/30 * * * *",
                "TZ=Europe/Bucharest",
                "CLOUDFLARE_API_TOKEN=redacted"
            ],
            "Cmd": null,
            "Image": "favonia/cloudflare-ddns:1.15.0",
```

logs:

🌟 Cloudflare DDNS (v1.15.0-0-g864be42)
📖 Reading settings . . .
   🔸 Use default IP4_PROVIDER=cloudflare.trace
   🔸 Use default UPDATE_ON_START=true
   🔸 Use default DELETE_ON_STOP=false
   🔸 Use default CACHE_EXPIRATION=6h0m0s
   🔸 Use default TTL=1
   🔸 Use default DETECTION_TIMEOUT=5s
   🔸 Use default UPDATE_TIMEOUT=30s
📖 Checking settings . . .
📖 Current settings:
   🔧 Domains, IP providers, and WAF lists:
      🔸 IPv4-enabled domains:   mydomain1.eu, mydomain2.eu
      🔸 IPv4 provider:           cloudflare.trace
      🔸 WAF lists:               (none)
   🔧 Scheduling:
      🔸 Timezone:                Europe/Bucharest (currently UTC+02)
      🔸 Update schedule:         */30 * * * *
      🔸 Update on start?         true
      🔸 Delete on stop?          false
      🔸 Cache expiration:        6h0m0s
   🔧 Parameters of new DNS records and WAF lists:
      🔸 TTL:                     1 (auto)
      🔸 Proxied domains:        mydomain1.eu, mydomain2.eu
      🔸 Unproxied domains:       (none)
      🔸 DNS record comment:      (empty)
      🔸 WAF list description:    (empty)
   🔧 Timeouts:
      🔸 IP detection:            5s
      🔸 Record/list updating:    30s
🌐 Detected the IPv4 address xxxxxxx
🤷 The A records of domain1.eu are already up to date
📡 Updated a stale A record of domain2.eu (ID: redacted)
⏰ Checking the IP addresses in about 15m1s (17:00) . . .

There are two issues:  why is the ipv4 environment variable not respected  (docker inspect shows the env are correctly read) and why the latest versions are giving errors in https://api.cloudflare.com/cdn-cgi/trace, although the URL is loading fine in a browser?
