### ISSUE TITLE
Support filtering by WAF item comments

### ISSUE THREAD

**Issue by favonia** [favonia/cloudflare-ddns#1044]
This feature request is to implement #819 and then add another option, likely `WAF_LIST_ITEM_COMMENT_AS_FILTER`, to use comments as filters. The use case is to have multiple instances updating the same WAF list. This has been on my mind, but I chose not to implement it for the sake of simplicity until a user requested it. @az1611

P.S.: For DNS records, we can also consider `RECORD_COMMENT_AS_FILTER` (but not now). I feel tags are more appropriate for filtering DNS records, but most users do not have access to them. 😅

There are a few technical issues to discuss:

1. For WAF lists, pathological race conditions could lead to very confusing results (that is, when two instances are updating the lists at almost the same time). I haven't checked the code carefully.
2. Isn't the name `WAF_LIST_ITEM_COMMENT_AS_FILTER` a bit too long? 🤔

**Comment by archef2000** [comment]
I don't know if it is in scope for this FR, but I would like to update one record with 3 nodes so that it is load balanced between them. I also don't want the records of the other nodes to be cleared by each other. There `RECORD_COMMENT_AS_FILTER` would be usefull to only let each node see it own record.

**Comment by favonia** [comment]
@archef2000 I opened an issue for you. However, as mentioned earlier, I have other priorities to take care of now. 😔

**Comment by macf0x** [comment]
+1

The free CF teir only allows a single list. Dedicating this limited resource to a single use is not ideal.

Using the comment to track the DDNS IP in the list would be much better.

**Comment by favonia** [comment]
@macf0x Thanks for the comment. How do you feel about the option name `WAF_LIST_ITEM_COMMENT_AS_FILTER`? It is a bit long to my taste.

PS: The technical challenge is to make sure race conditions are _impossible._

**Comment by archef2000** [comment]
My [current implementation](https://github.com/archef2000/cloudflare-ddns) uses these environment variables to use the feature:
```
  cloudflare:
    image: archef2000/cloudflare-ddns
    networks:
      - outside
    environment:
      - DOMAINS=***,{{.Node.Hostname}}.***
      - PROXIED=false
      - TTL=60
      - CACHE_EXPIRATION=10s
     
      - RECORD_COMMENT={{.Node.Hostname}}
      - RECORD_COMMENT_AS_FILTER=true
    deploy:
      mode: global
```
