### ISSUE TITLE
Failed to check the existence of a zone named XXXXXXXXXXX.es: Invalid request headers (6003)

### ISSUE THREAD

**Issue by lordraiden** [favonia/cloudflare-ddns#1053]
Why do I get this error? what I'm doing wrong?

![Image](https://github.com/user-attachments/assets/33e4aeea-9a0d-4ed5-bb9d-6b293fe59ed3)

Cloudflare config

![Image](https://github.com/user-attachments/assets/1ebe3639-00b0-4030-97f5-79af66ff4aac)

Docker compose section

```
  cloudflare-ddns:
    container_name: ${cloudflare_ddns_name}
    image: favonia/cloudflare-ddns:latest
    read_only: true
    cap_drop: [all]
    networks:
      eth1:
        ipv4_address: ${cloudflare_ddns_ip}
    volumes:
      - ${dockerdir}/DDNS:/config
    environment:
      - TZ
      - UPDATE_CRON=@every 5m
      - UPTIMEKUMA=https://uptimekuma.xxxxxxxxxxx.es/api/push/OBKP8tLH4y?status=up&msg=OK&ping=
      - CLOUDFLARE_API_TOKEN=CF_DNS_API_TOKEN # Your Cloudflare API token
      - DOMAINS=xxxxxxxxxxxxxxxes # Your domains (separated by commas)ç
      - IP6_PROVIDER=none
      - PROXIED=false        # Tell Cloudflare to cache webpages and hide your IP (optional)


## Secrets ####################################################

  CF_DNS_API_TOKEN:
    file: $SECRETSDIR/CF_DNS_API_TOKEN
```

Does it support secrets?
