### ISSUE TITLE
Line Seperated SHOUTRRR fails to recognize multiple items

### ISSUE THREAD

**Issue by arjunrbery** [favonia/cloudflare-ddns#1060]
Hello,

I'm using the following docker-compose file my setup. However, the SHOUTRRR integration is providing the following output.

`😞 Failed to notify shoutrrr service(s): error sending message to recipient: error setting RCPT: 501 5.1.3 Bad recipient address syntax`

```
services:
  cloudflare-ddns:
    image: favonia/cloudflare-ddns:latest
    network_mode: host
    # This bypasses network isolation and makes IPv6 easier (optional; see below)
    restart: always
    # Restart the updater after reboot
    user: "1000:1000"
    # Run the updater with specific user and group IDs (in that order).
    # You can change the two numbers based on your need.
    read_only: true
    # Make the container filesystem read-only (optional but recommended)
    cap_drop: [all]
    # Drop all Linux capabilities (optional but recommended)
    security_opt: [no-new-privileges:true]
    # Another protection to restrict superuser privileges (optional but recommended)
    environment:
      OtherENVVaribles:LoadedHere
      SHOUTRRR: >
        smtp://sender@example.com:password@smtp.example.com:587/?from=sender@example.com&to=recipient@example.com
        ntfy://user:password@ntfy.sh/server_alerts_custom
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
```
Should I be using a different method to notate the newlines for multiple destinations?

Thank you
