### ISSUE TITLE
Bug: can't work with Docker secrets

### ISSUE THREAD

**Issue by V33m** [favonia/cloudflare-ddns#172]
Hi, what an awesome service you have created!

I've a minor thing as I can't seem to figure out how to fully disable ipv6 using docker-compose. Hence my logs are full of
```
😞 Failed to send HTTP(S) request to "https://[REMOVED]/cdn-cgi/trace": Get "https://[REMOVED]/cdn-cgi/trace": dial tcp [REMOVED]:443: connect: cannot assign requested address
😞 Failed to detect the IPv6 address
🔧 If you are using Docker, Kubernetes, or other frameworks, IPv6 networks often require additional setups.
🔧 Read more about IPv6 networks in the README at https://github.com/favonia/cloudflare-ddns
```

Under highlights it says "Ability to enable or disable IPv4 and IPv6 individually." I've tried to disable ipv6 by adding the following to the env in docker-compose: `      - IP6_PROVIDER=none`

If I set `IP4_POLICY=none` which is listed as a valid value in the readme I get:
```
   🔸 Use default IP4_POLICY=cloudflare.trace
   😡 Failed to parse "none": not a valid policy
```

**Comment by favonia** [comment]
Hi! Thanks for the reporting. There was a recent change in the names of the environment variables by PR #167 so that the README on the main branch (which is about the development version) does not match the stable version you are using. (The older README is at https://github.com/favonia/cloudflare-ddns/blob/v1.4.0/README.markdown.) Sorry about the trouble. While the developer recognizes both `IP6_POLICY=unmanaged` (with a warning) and the new `IP6_PROVIDER=none`, the stable (older) version only recognizes `IP6_POLICY=unmanaged`. That's why `IP6_PROVIDER=none` has no effects.

I guess the development version is stable enough for another release (there's some internal rewrite), and in the meanwhile you could use `IP6_POLICY=unmanaged` to disable IPv6.

**Comment by V33m** [comment]
Cool, thanks! One more thing, I'm using secrets for my other Docker services, yet I can't seem to get it to work as usual. Any suggestions? All secrets are in a secrets folder and is defined correctly in the docker-compose file (I'm using 8 secrets and for multiple containers)

```
  cloudflare-ddns:
    image: favonia/cloudflare-ddns:latest
    network_mode: host
    restart: always
    security_opt:
      - no-new-privileges:true
    environment:
      - PGID=1001
      - PUID=1002
      - CF_API_TOKEN_FILE=/run/secrets/cf_api_token
      - DOMAINS=REMOVED
      - PROXIED=true
      - IP6_POLICY=unmanaged
    secrets:
      - cf_api_token
```

Logs:
```
📖 Reading settings . . .
   😡 Failed to read "/run/secrets/cf_api_token": open /run/secrets/cf_api_token: invalid argument
```
