### ISSUE TITLE
[Feature request] Single update execution mode / disable cron

### ISSUE THREAD

**Issue by bodak** [favonia/cloudflare-ddns#409]
Thanks for developing cloudflare-ddns. I have it happily deployed in a Kubernetes cluster.
I would like to migrate the scheduling from your internal Go based cron to running it with Kubernetes' native [CronJob](https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/).

How difficult would it be to implement a single update mode? In other words, the binary would not run continiously, but execute a single time and just terminate successfully. This would free up node resources until the next scheduled run.

**Comment by bodak** [comment]
> @bodak Thanks for the suggestion. I cannot think of any immediate difficulty, maybe except for deciding the desired configuration for it? One idea is to introduce new values for `UPDATE_CRON` such as
> 
> ```
> UPDATE_ON_START=true
> UPDATE_CRON=@disabled
> ```
> 
> The other idea is to take a new environment variable. Any suggestion helps because I am not a native speaker 😅 BTW, I should let you know that the current caching will stop working for the obvious reason---the updater will have to retrieve all data every time. There could lead to more network traffic.
> 
> PS: The current "workaround" is to use `UPDATE_ON_START=true` and a value of `UPDATE_CRON` that could not be triggered in many years (because the current Go-based library https://github.com/robfig/cron that I haven't replaced yet will give up when the next time is many years ahead).
> 
> PPS: I planned to replace the cron library and the progress is tracked by #74.

My 2 cents would be just to make a new environment variable:
```
RUN_ONCE=true
```
If the environment variable is **set** and **value** is true, you execute the update and **terminate**. It is important that the container finishes.

Replying to PS: That would not work, since your `ddns` binary would still continue running thereby keeping the container in a running state.
My first idea was to overwrite your Dockerfile's command, but you have integrated `cron` into the binary.
https://github.com/favonia/cloudflare-ddns/blob/main/Dockerfile#L22

**Comment by favonia** [comment]
> Replying to PS: That would not work, since your `ddns` binary would still continue running thereby keeping the container in a running state.

I'd like to clarify the workaround first: yes it will stop, due to how https://github.com/robfig/cron schedules things between 5 years and 11 years due to the bug at https://github.com/robfig/cron/issues/395. (This is one of many reasons why I want to replace the library, though in 99% cases it is working fine.) Another hack is to use `UPDATE_CRON='0 0 30 2 *'` (every Feb 30th midnight) to practically disable the cron. In either case, the updater **will terminate** when it is impossible to schedule the next update. :-) To clarify, I don't think any of these workarounds is good, but I'm surprised that they didn't work in your case. Did you try any of them?

> My 2 cents would be to just make a new environment variable:
>
> RUN_ONCE=true

My hesitation with introducing `RUN_ONCE=true` is that many option combinations would be undefined. In particular, all of these should be banned:
```
UPDATE_ON_START=false
RUN_ONCE=true
```
```
UPDATE_CRON=@yearly
RUN_ONCE=true
```
The meaning of `UPDATE_ON_START` and `UPDATE_CRON` can no longer be independently defined due to the power differentiation between `RUN_ONCE` and other related options. It is convenient when the "most powerful" option is what you want, but then the overriding relations can be complicated. I did not mean to put the design burden on you @bodak (I enjoy coming up with a modular/composable design) but merely to explain why I have not gone with this route yet.

Another minor point is that all API caching should be disabled if it's run only once.

**Comment by bodak** [comment]
Thanks for the clarification. I was not aware of the bug supporting the workaround.
Let me try to implement it and let you know.

I understand your point and `UPDATE_CRON=@disabled` is also fine. It would need `UPDATE_ON_START=true` as you said, so you have the strict combination of two feature flags achieving the behavior. I was merely proposing the seemingly simplest solution without having a good understanding of your code architecture.

**Comment by favonia** [comment]
> I was merely proposing the seemingly simplest solution without having a good understanding of your code architecture.

I like your proposal if there were no interactions with other existing features. As for the code---I think it is quite easy (for me) to implement whatever configuration parser or cool features we want. I am only struggling with the UI design. :-) For that I need your (the user's) feedback. Let me know if you get some other ideas.

I will try to make a PR with `UPDATE_CRON=@disabled` soon, then. `UPDATE_ON_START=true` is the default. Using `UPDATE_CRON=@disabled` with `DELETE_ON_STOP=true` will result into an error. (I will check other combinations more carefully later.)

**Comment by bodak** [comment]
I have tried your suggestion just now. With env variable set to `UPDATE_CRON='0 0 30 2 *'`, the container indeed terminates with `😡 No scheduled updates in near future 👋 Bye!`

Unfortunately since the container exits with an error, Kubernetes immediately retries the job.
```
cloudflare-manual-lsqlt-fscjg   0/1     Error     0          6m36s
cloudflare-manual-lsqlt-gr8ff   0/1     Error     0          6m27s
cloudflare-manual-lsqlt-lz8z8   0/1     Error     0          6m9s
cloudflare-manual-lsqlt-hz6hl   0/1     Error     0          5m40s
cloudflare-manual-lsqlt-65nnp   0/1     Error     0          5m13s
cloudflare-manual-lsqlt-m8g6w   0/1     Error     0          3m45s
cloudflare-manual-lsqlt-jvrjn   0/1     Error     0          57s
```


Deployment code used for reference:
```
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cloudflare-ddns
  namespace: default
spec:
  schedule: '@hourly'
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: cloudflare-ddns
        spec:
          containers:
            - name: cloudflare-ddns
              image: favonia/cloudflare-ddns:1.8.4
              imagePullPolicy: IfNotPresent
              envFrom:
              - secretRef:
                  name: cloudflare-ddns
              env:
                - name: UPDATE_CRON
                  value: "0 0 30 2 *"
                - name: UPDATE_ON_START
                  value: "true"
              resources:
                requests:
                  memory: 10Mi
                limits:
                  memory: 15Mi
              securityContext:
                allowPrivilegeEscalation: false
                runAsUser: 1000
                runAsGroup: 1000
          restartPolicy: Never
```
