### ISSUE TITLE
CF_API_TOKEN_FILE error

### ISSUE THREAD

**Issue by Niaw** [favonia/cloudflare-ddns#493]
Hi favonia,

I keep having errors when trying to implement my Cloudflare API token as an external file. I tried with a secret file (without Swarm) and also with CF_API_TOKEN_FILE, but nothing works.

Rootless Docker, tried the file in another folder, and also in the same directory as my compose file.

Compose file:
```
version: "3"

services:
  cloudflare-ddns:
    image: favonia/cloudflare-ddns:latest
    container_name: cloudflare-ddns
    network_mode: host
    restart: always
    cap_add:
      - SETUID
      - SETGID
    cap_drop:
      - all
    read_only: true
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=1000
      - PGID=1000
      - CF_API_TOKEN_FILE=my_cloudflare_api_token_file
      - DOMAINS=example.org,www.example.org,example.io
      - PROXIED=true
```

Logs:
cloudflare-ddns  | 🌟 Cloudflare DDNS (v1.9.2-0-g039b8d2)
cloudflare-ddns  | 🥷 Dropping privileges . . .
cloudflare-ddns  | 📖 Reading settings . . .
cloudflare-ddns  |    😡 Failed to read "my_cloudflare_api_token_file": open my_cloudflare_api_token_file: no such file or directory
cloudflare-ddns  | 👋 Bye!

Same with:
`      - CF_API_TOKEN_FILE=$PWD/my_cloudflare_api_token_file`

And when I try with:
`      - CF_API_TOKEN_FILE=./my_cloudflare_api_token_file`

cloudflare-ddns  | 🌟 Cloudflare DDNS (v1.9.2-0-g039b8d2)
cloudflare-ddns  | 🥷 Dropping privileges . . .
cloudflare-ddns  | 📖 Reading settings . . .
cloudflare-ddns  |    😡 Failed to read "./my_cloudflare_api_token_file": stat ./my_cloudflare_api_token_file: invalid argument
cloudflare-ddns  | 👋 Bye!

I don't know what I am doing wrong.

Thanks!
