### ISSUE TITLE
1.1.1.1 appears to be blocked or hijacked by your ISP or your router

### ISSUE THREAD

**Issue by Aiakio** [favonia/cloudflare-ddns#568]
Hello there

I need help troubleshooting, please.
Since for a lot of other people this is working, I fully expect, that the issue is somewhere in my network, i just don't know where or how to look / find it and need help with diagnosing.
Just in case this is relevant information: Im running this on a Synology DS1520+ NAS behind a Synology RT6600ax Router.

I get
```
📖 Checking settings . . .
📖 Checking 1.1.1.1 . . .
   😞 1.1.1.1 appears to be blocked or hijacked by your ISP or your router
   😊 1.0.0.1 appears to be blocked or hijacked as well; sticking to 1.1.1.1
```
but i am not sure what that means. I do not (knowingly) block 1.1.1.1 or 1.0.0.1 on my network. And i am not sure if my router hijacked this (not sure what that means in the first place.). If i surf to 1.1.1.1 or 1.0.0.1 on a web browser, the page loads normally.

Sorry for this. Basically, I'm in the middle of learning this kind of stuff. But i couldn't figure that one out so far and need some help.

This is the entire log:
```
🌟 Cloudflare DDNS (v1.9.4-0-g68dc1f3)
🥷 Dropping privileges . . .
📖 Reading settings . . .
   🔸 Use default IP4_PROVIDER=cloudflare.trace
   🔸 Use default IP6_PROVIDER=cloudflare.trace
   🔸 Use default UPDATE_CRON=@every 5m
   🔸 Use default UPDATE_ON_START=true
   🔸 Use default DELETE_ON_STOP=false
   🔸 Use default CACHE_EXPIRATION=6h0m0s
   🔸 Use default TTL=1
   🔸 Use default DETECTION_TIMEOUT=5s
   🔸 Use default UPDATE_TIMEOUT=30s
📖 Checking settings . . .
📖 Checking 1.1.1.1 . . .
   😞 1.1.1.1 appears to be blocked or hijacked by your ISP or your router
   😊 1.0.0.1 appears to be blocked or hijacked as well; sticking to 1.1.1.1
📖 Current settings:
   🔧 Domains and IP providers:
      🔸 IPv4 domains:            [REDACTED]
      🔸 IPv4 provider:           cloudflare.trace
      🔸 IPv6 domains:            [REDACTED]
      🔸 IPv6 provider:           cloudflare.trace
   🔧 Scheduling:
      🔸 Timezone:                UTC (UTC+00 now)
      🔸 Update frequency:        @every 5m
      🔸 Update on start?         true
      🔸 Delete on stop?          false
      🔸 Cache expiration:        6h0m0s
   🔧 New DNS records:
      🔸 TTL:                     1 (auto)
      🔸 Proxied domains:         (none)
      🔸 Unproxied domains:       [REDACTED]
   🔧 Timeouts:
      🔸 IP detection:            5s
      🔸 Record updating:         30s
😞 Failed to send HTTP(S) request to "https://1.1.1.1/cdn-cgi/trace": GET https://1.1.1.1/cdn-cgi/trace giving up after 1 attempt(s): context deadline exceeded
😞 Failed to detect the IPv4 address
🔧 If your network does not support IPv4, you can disable it with IP4_PROVIDER=none
😞 Failed to send HTTP(S) request to "https://[2606:4700:4700::1111]/cdn-cgi/trace": GET https://[2606:4700:4700::1111]/cdn-cgi/trace giving up after 1 attempt(s): context deadline exceeded
😞 Failed to detect the IPv6 address
🔧 If you are using Docker or Kubernetes, IPv6 often requires additional setups
🔧 Read more about IPv6 networks at https://github.com/favonia/cloudflare-ddns
🔧 If your network does not support IPv6, you can disable it with IP6_PROVIDER=none
⏰ Checking the IP addresses in about 4m49s . . .
```

And this is my docker compose yaml deployed via Portainer:
```
    cloudflare-ddns:
        container_name: cloudflare-ddns
        image: favonia/cloudflare-ddns:latest
        network_mode: host
        restart: unless-stopped
        cap_add:
            - SETUID
            - SETGID
        cap_drop:
            - all
        read_only: true
        security_opt:
            - no-new-privileges:true
        environment:
            - PUID=1026
            - PGID=100
            - CF_API_TOKEN=[REDACTED]
            - DOMAINS=[REDACTED]
            - PROXIED=false
```
