### ISSUE TITLE
'A' record not updating when log claims it is up to date

### ISSUE THREAD

**Issue by gagestinson** [favonia/cloudflare-ddns#680]
Hello,
I am setting this up in a portainer stack. The log is claiming that the 'A' record I specified in the compose file is already up to date when it is not. Please let me know if there are any more details you need from me.

 Log:
``🌐 Detected the IPv4 address: W.X.Y.Z``
``🤷 The A records of "*.website.com" are already up to date``
``⏰ Checking the IP addresses in about 5m0s . . .``
``🌐 Detected the IPv4 address: W.X.Y.Z``
``🤷 The A records of "*.website.com" are already up to date``
``⏰ Checking the IP addresses in about 5m0s . . . ``

Compose:
```
---
version: "3"
services:
  cloudflare-ddns:
    image: favonia/cloudflare-ddns:latest
    network_mode: host
    # This makes IPv6 easier; see below
    restart: unless-stopped
    # Restart the updater after reboot
    cap_add:
      - SETUID
        # Capability to change user ID; needed for using PUID
      - SETGID
        # Capability to change group ID; needed for using PGID
    cap_drop:
      - all
      # Drop all other capabilities
    read_only: true
    # Make the container filesystem read-only
    security_opt:
      - no-new-privileges:true
        # Another protection to restrict superuser privileges
    environment:
      - PUID=1000
        # Run the updater with user ID 1000
      - PGID=1000
        # Run the updater with group ID 1000
      - CF_API_TOKEN=XXX
        # Your Cloudflare API token
      - DOMAINS=*.website.com
        # Your domains (separated by commas)
      - PROXIED=true
        # Tell Cloudflare to cache webpages and hide your IP
      - IP6_PROVIDER=none
```
