### ISSUE TITLE
Failed to find zone & current A records

### ISSUE THREAD

**Issue by tfer6** [favonia/cloudflare-ddns#691]
Hi,  I was using [oznu/cloudflare-ddns](https://github.com/oznu/docker-cloudflare-ddns) previously and was attempting to migrate to your solution, however I keep getting this error upon deployment

😞 Failed to find the zone of "sub.domain.com"
😞 Failed to retrieve the current A records of "sub.domain.com"

Here is my compose, basically verbatim of your example.
```
version: "3"
services:
  cloudflare-ddns:
    image: favonia/cloudflare-ddns:latest
    network_mode: host
    # This makes IPv6 easier; see below
    restart: always
    # Restart the updater after reboot
    cap_add:
      - SETUID # Capability to change user ID; needed for using PUID
      - SETGID # Capability to change group ID; needed for using PGID
    cap_drop:
      - all
      # Drop all other capabilities
    read_only: true
    # Make the container filesystem read-only
    security_opt:
      - no-new-privileges:true # Another protection to restrict superuser privileges
    environment:
      - PUID=1000 # Run the updater with user ID 1000
      - PGID=1000 # Run the updater with group ID 1000
      - CF_API_TOKEN=token # Your Cloudflare API token
      - DOMAINS=sub.domain.com, # Your domains (separated by commas)
      - CF_ACCOUNT_ID=abc@xyz.com
      - IP6_PROVIDER=none
      
```
I'm guessing I'm just missing something somewhere, so any help or a point in the right direction is appreciated.

Full log slightly redacted.
```
🌟 Cloudflare DDNS (v1.11.0-0-g52d2019)
🥷 Dropping privileges . . .
📖 Reading settings . . .
   🔸 Use default IP4_PROVIDER=cloudflare.trace
   🔸 Use default UPDATE_CRON=@every 5m
   🔸 Use default UPDATE_ON_START=true
   🔸 Use default DELETE_ON_STOP=false
   🔸 Use default CACHE_EXPIRATION=6h0m0s
   🔸 Use default TTL=1
   🔸 Use default PROXIED=false
   🔸 Use default DETECTION_TIMEOUT=5s
   🔸 Use default UPDATE_TIMEOUT=30s
📖 Checking settings . . .
📖 Checking 1.1.1.1 . . .
   😊 1.1.1.1 appears to be working
📖 Current settings:
   🔧 Domains and IP providers:
      🔸 IPv4 domains:            sub.domain.com
      🔸 IPv4 provider:           cloudflare.trace
   🔧 Scheduling:
      🔸 Timezone:                UTC (UTC+00 now)
      🔸 Update frequency:        @every 5m
      🔸 Update on start?         true
      🔸 Delete on stop?          false
      🔸 Cache expiration:        6h0m0s
   🔧 New DNS records:
      🔸 TTL:                     1 (auto)
      🔸 Proxied domains:         (none)
      🔸 Unproxied domains:       sub.domain.com
   🔧 Timeouts:
      🔸 IP detection:            5s
      🔸 Record updating:         30s
🌐 Detected the IPv4 address: my ip
😞 Failed to find the zone of "sub.domain.com"
😞 Failed to retrieve the current A records of "sub.domain.com"
⏰ Checking the IP addresses in about 4m59s . . .
```
