### ISSUE TITLE
Hanging or crashing under Docker within LXC (Linux containers)

### ISSUE THREAD

**Issue by fendle** [favonia/cloudflare-ddns#707]
Hi,
my IP is not longer update in cloudflare and in my docker logs I see only this message.

cloudflareddns-cloudflare-ddns-1  | 🌟 Cloudflare DDNS (v1.11.0-0-g52d2019)
cloudflareddns-cloudflare-ddns-1  | 🥷 Dropping privileges . .

I used the standard docker compose configuration.

Thanks .

**Comment by favonia** [comment]
@fendle Hi, may I have your confirmation on these?

1. The same version (1.11.0) with the same configuration used to be working fine.
2. However, for some reasons, it is no longer working now.
3. Your other Docker images are working as expected.
4. "🥷 Dropping privileges . ." is the last message you saw. In particular, it is _not_ "🥷 Dropping privileges . . ." (with three dots).

**Comment by favonia** [comment]
@fendle Your configuration _might_ help, although the phenomenon you described does not sound like a misconfiguration of the tool. (Please hide sensitive information such as your domain names and API tokens.)

**Comment by fendle** [comment]
Hi @favonia,
I have really the standard config, I changed only the API key and enter all my subdomains.
Is there a more detailed log which can be seen directly in the docker?

**Comment by favonia** [comment]
@fendle The default configuration will already show the maximum amount of information. Could you possibly also check the things I wish to confirm in the other comment? Thank you!

**Comment by favonia** [comment]
@fendle Hi, I wonder if you could help me understand your problem better? 

1. Did the same configuration work before?
2. Are your other Docker images are working as expected?
3. Are you able to run the Docker container alone without using docker-compose?

**Comment by fendle** [comment]
Hi @favonia ,
here my Feedback
1. The configuration was working before
2. My other docker images are working as expected
3. I haven't tried it yet, but can do it.

It would be only helpful, why it can be executed to have a hint.#
The message "🥷 Dropping privileges . . ." is unfortauntely not really helpful :(

**Comment by favonia** [comment]
@fendle Thank you. I feel I still need more information, and your testing without Docker compose will help a lot. I can think of the following possible causes, but all of them sound super weird to me:

1. For whatever reasons, the tool was stuck at some system call for dropping privileges; or,
2. For some reason, the tool was actually working as expected, but the logging was somehow stopped; or,
3. For some reason, the Docker container was paused/stopped.

_Theoretically_, "dropping privileges" should not involve any system calls that could ever be blocked, so Cause 1 is theoretically impossible. However, other causes are equally strange as well. Your experiment to run the tool without Docker compose---or even without Docker---can help check whether Causes 2 and/or 3 is the culprit.

I see that you are suggesting more detailed logging. That's actually technically difficult. The dropping involves lots of ugly low-level Linux system calls and it is annoying (maybe impossible, actually) to print out each of them. Some of them are buried inside the Go standard library to maintain consistency between threads. A more reliable way is to use tools such `strace` to monitor the cloudflare-ddns (run _without_ Docker) to see which system call might be blocking the entire program. Again, none of these system calls should be blocking as far as I can see!

Another thing that could be incredibly helpful is to recall any change you might have made that caused the tool to stop working. Do you remember anything that might have affect your Docker?

**Comment by este1561997** [comment]
Hello,
same problem for me, DNSs are not updated and uptimekuma is not working too.

compose.yml:
```
services:
  cloudflare-ddns:
    image: favonia/cloudflare-ddns:latest
    container_name: cloudflare-ddns
    network_mode: host
    restart: always
    cap_add:
      - SETUID
      - SETGID
    cap_drop:
      - all
    read_only: true
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - CF_API_TOKEN=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      - DOMAINS=xxxx.org,yyyy.xxxx.org
        # Your domains (separated by commas)
      - PROXIED=false
      - UPTIMEKUMA="https://zzzz.xxxx.org/api/push/LvzcnABuqW?status=up&msg=OK&ping="
```

logs:
```
🌟 Cloudflare DDNS (v1.11.0-0-g52d2019)
🥷 Dropping privileges . . .
```

**Comment by favonia** [comment]
@este1561997 Could you try any of the following? (@fendle I apologize---I should have provided more detailed instructions for you to test things.)

1. Directly run the DDNS updater using this in the command line:

```bash
CF_API_TOKEN=YOUR-CLOUDFLARE-API-TOKEN \
  DOMAINS=xxxx.org,yyyy.xxxx.org \
  TZ=Europe/Rome
  UPTIMEKUMA="https://zzzz.xxxx.org/api/push/LvzcnABuqW?status=up&msg=OK&ping="
  go run github.com/favonia/cloudflare-ddns/cmd/ddns@latest
```

2. OR, downgrade the version to v.1.10.1 (without support of Uptime Kuma):

Change `latest` to `1.10.1` as follows:

```yaml
services:
  cloudflare-ddns:
    image: favonia/cloudflare-ddns:1.10.1
    container_name: cloudflare-ddns
    network_mode: host
    restart: always
    cap_add:
      - SETUID
      - SETGID
    cap_drop:
      - all
    read_only: true
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - CF_API_TOKEN=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      - DOMAINS=xxxx.org,yyyy.xxxx.org
        # Your domains (separated by commas)
      - PROXIED=false
      - UPTIMEKUMA="https://zzzz.xxxx.org/api/push/LvzcnABuqW?status=up&msg=OK&ping="
```

3. OR, downgrade and run it without Docker:

```bash
CF_API_TOKEN=YOUR-CLOUDFLARE-API-TOKEN \
  DOMAINS=xxxx.org,yyyy.xxxx.org \
  TZ=Europe/Rome
  go run github.com/favonia/cloudflare-ddns/cmd/ddns@v1.10.1
```

Testing _any_ of these will help. Thank you!

**Comment by massijay** [comment]
Hi @favonia, I tried your suggestions and downgrading didn't fix the problem, however if I try to run directly without docker I get this error message
```
😦 Failed to reset group IDs to only 1000; current ones: 1000, 27, 100, 995
SIGSYS: bad system call
PC=0x46b8d7 m=2 sigcode=0
```

**Comment by favonia** [comment]
@massijay Thank you for your testing!!! Now I have much better idea about what might be going on. May I ask if the `edge` version fixes it? I couldn't devote enough time before the semester ends to implement any feature, but if the new Go runtime (1.22) or the new libcap fixes the issue, a new release seems to be worth it. It could also be that Docker is the culprit... :thinking:

Anyway, please try the latest development version, using "edge" instead of "latest":
```
services:
  cloudflare-ddns:
    image: favonia/cloudflare-ddns:edge
    container_name: cloudflare-ddns
    network_mode: host
    restart: always
    cap_add:
      - SETUID
      - SETGID
    cap_drop:
      - all
    read_only: true
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - CF_API_TOKEN=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      - DOMAINS=xxxx.org,yyyy.xxxx.org
        # Your domains (separated by commas)
      - PROXIED=false
      - UPTIMEKUMA="https://zzzz.xxxx.org/api/push/LvzcnABuqW?status=up&msg=OK&ping="
```
I plan release a version that removes all functionality of privilege dropping so that at least it would work (this is tracked by #728).
