### ISSUE TITLE
Kubernetes securityContext "runAsNonRoot" not working

### ISSUE THREAD

**Issue by chrede88** [favonia/cloudflare-ddns#828]
Mostly leaving this here for others that might have the same issue.

Since `v1.13` the default user is no longer set, which means the container will run as root! Not good, also not needed.
The quick way to fix this is to include a `securityContext` in the deployment manifest, like so:
```yaml
spec:
  template:
    spec:
      securityContext:
        runAsNonRoot: true
```

But this doesn't work. Setting the user/group ID does however work. I'm not 100% sure why, as `runAsNonRoot` should just pick a non-zero ID at random. But there is probably something I'm missing.
This will work as expected:
```yaml
spec:
  template:
    spec:
      securityContext:
        runAsUser: <someNonZeroNumber>
        runAsGroup: <someNonZeroNumber>
```
