### ISSUE TITLE
Docker compose with no-new-privileges does not work

### ISSUE THREAD

**Issue by jogerj** [favonia/cloudflare-ddns#922]
The README.md specifies that `security_opt` item is optional, but when it's set to `[no-new-priveleges:true]`, the container would not start. Removing the line allows the container to start normally. If this option was working in the past, either something has changed or my setup does not support it for some reason.

Running on Ubuntu 22.04.4 LTS (Jammy Jellyfish) inside proxmox (`pve-manager/8.2.4/faa83925c9641325 (running kernel: 6.8.8-4-pve)`)

`docker-compose.yml`:

```
name: cloudflare
services:
  ddns:
    image: favonia/cloudflare-ddns:1.14.0
    network_mode: host
    restart: always
    user: "1000:1000"
    read_only: true
    cap_drop: [all]
    security_opt: [no-new-privileges:true] # commenting out this line removes fixes it
    environment:
      CF_API_TOKEN: ${CF_API_TOKEN} # from .env
      DOMAINS: foo.example.com,bar.example.com
      PROXIED: "false"
      IP6_PROVIDER: "none"
```

`docker compose logs`:

```
cloudflare-ddns-1  | exec /bin/ddns: operation not permitted
cloudflare-ddns-1  | exec /bin/ddns: operation not permitted
cloudflare-ddns-1  | exec /bin/ddns: operation not permitted
...
```

`uname -a`:

```
Linux foo.example.com 5.15.0-119-generic #129-Ubuntu SMP Fri Aug 2 19:25:20 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

`docker version`:

```
Client:
 Version:           24.0.5
 API version:       1.43
 Go version:        go1.20.14
 Git commit:        ced0996
 Built:             Tue Jun 25 22:37:33 2024
 OS/Arch:           linux/amd64
 Context:           default

Server:
 Engine:
  Version:          24.0.5
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.14
  Git commit:       a61e2b4
  Built:            Tue Jun 25 22:38:06 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.12
  GitCommit:
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
