### ISSUE TITLE
Improve the README structure

### ISSUE THREAD

**Issue by NotaInutilis** [favonia/cloudflare-ddns#983]
Hi! I've got an issue with passing the cloudflare API token via a secret on docker compose file. It works when pasting it as an environment variable but outputs an error `😞 Failed to check the existence of a zone named DOMAIN: Invalid request headers (6003)` when using a secret. I first asked for help on the formatting of my compose file, but it doesn't seem that there is any issue with it so instead of bashing my head on my keyboard, I'm asking for some help here.

```
services:
  cloudflare-ddns:
    container_name: cloudflare-ddns
    image: favonia/cloudflare-ddns
    restart: always
    user: ${USER}
    read_only: true
    cap_drop: [all]
    security_opt: [no-new-privileges:true]
    environment:
      - CLOUDFLARE_API_TOKEN=/run/secrets/CLOUDFLARE_API_TOKEN
      - DOMAINS=DOMAIN
      - PROXIED=false
    secrets:
      - CLOUDFLARE_API_TOKEN

secrets:
  CLOUDFLARE_API_TOKEN:
    file: ./secrets/CLOUDFLARE_API_TOKEN.txt
```
